# This is a basic workflow to help you get started with Actions

name: Test, Build and Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8
    - name: Test with Maven
      run: mvn test -Dmule.env="dev" --settings .maven/settings.xml
    - name: Upload MUnit reports
      uses: actions/upload-artifact@v4
      with:
        name: munit-test-reports
        path: target/site/munit/coverage

  build:
    needs: test
    runs-on: windows-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: 8
    - name: Build with Maven
      run: mvn -B package --file.pom.xml -Dmule.env="dev" -DskipMunitTests
    - name: Upload artifact 
      uses: actions/upload-artifact@v4
      with:
          name: artifacts
          path: target/*.jar
          
  deploy:
    needs: build
    runs-on: windows-latest
    steps:    
    - name: Checkout this repo
      uses: actions/checkout@v3
    - name: Download the JAR File
      uses: actions/download-artifact@v3
      with:
        name: artifacts
    - name: Deploy to Dev
      env:
        CLIENTID: ${{ secrets.anypoint_platform_clientId }}
        CLIENTSECRET: ${{ secrets.anypoint_platform_clientSecret }}
      run: mvn deploy -DskipMunitTests -DmuleDeploy -DClientId="$CLIENTID" -DClientSecret="$CLIENTSECRET" -DGrantType="client_credentials" -Denvironment="DEV" -Dmule.env="dev"
